### ISSUE TITLE
bin is now in .gitignore

### ISSUE THREAD

**Issue by Pluckerpluck** [frifox/gw2dps#10]
While I can build this myself, I thought I'd notify you that binaries are no longer available as the bin file is ignored.

Might want to change that so people less tech savvy can still use this.

**Comment by Cubimon** [comment]
In general code repositories don't contain binaries,  that's why I removed them. Git does not handle binary diffs well so the repository gets fast really huge (atm the repo has about 18 mb). Instead GitHub offers a better method for developers to add releases at https://github.com/user/project/releases. So we should wait until frifox uploads his releases there.

**Comment by Pluckerpluck** [comment]
Fair enough. That makes sense

**Comment by frifox** [comment]
Moved binaries and redistributables to releases page.
