### ISSUE TITLE
Locked no longer works

### ISSUE THREAD

**Issue by Pluckerpluck** [frifox/gw2dps#33]
Locking a target doesn't seem to do anything at all in the latest version (at least 64bit). Just acts as if not locked (except you get 0/0 instead of no box)

**Comment by frifox** [comment]
Thanks, I'll check it out tonight. Quite a few things got changed in past few weeks, may have broken something to cause this.

**Comment by hairys** [comment]
Just a hunch, but this is probably due to the pattern scanner for 64-bit not being as accurate as the 32-bit pattern scanner. My guess is he's throwing [RefreshDataAgent] errors, but since logging is disabled, we won't know. This is more or less a random occurrence. Try restarting the game and re-inject. See if that works for you.

**Comment by frifox** [comment]
Inactive issue, closing.
